#!/bin/bash
PASSWORD="qaqa"

#if password specified, replace default password
if [[ ! -z "$1" ]] ; then
    PASSWORD="$1"
fi

./dependencies/tools/bin/blackberry-deploy -installApp 169.254.0.1 ~/bin/device/APISmokeTest-new.bar -launchApp -password $PASSWORD
